name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1.1.0
        with:
          version: 14.x
      - name: npm install, test and build
        run: |
          npm ci
          npm run build
      - name: Codecov
        uses: codecov/codecov-action@v1.0.5
        with:
          # Repository upload token - get it from codecov.io
          token: ed035cb6-7365-4316-8c33-c4af92efbbb5

        env:
          CI: true
